-- begin PA_OPERATIONSTERMIN
alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID)^
alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_ERSTELLT_VON_ID foreign key (ERSTELLT_VON_ID) references PA_MITARBEITER(ID)^
create index IDX_PA_OPERATIONSTERMIN_PATIENT on PA_OPERATIONSTERMIN (PATIENT_ID)^
create index IDX_PA_OPERATIONSTERMIN_ERSTELLT_VON on PA_OPERATIONSTERMIN (ERSTELLT_VON_ID)^
-- end PA_OPERATIONSTERMIN
-- begin PA_OPERATIONSTERMIN_MITARBEITER_LINK
alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_MITARBEITER foreign key (MITARBEITER_ID) references PA_MITARBEITER (ID)^
alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_OPERATIONSTERMIN foreign key (OPERATIONSTERMIN_ID) references PA_OPERATIONSTERMIN (ID)^
-- end PA_OPERATIONSTERMIN_MITARBEITER_LINK
-- begin PA_ARBEITSTAG
alter table PA_ARBEITSTAG add constraint FK_PA_ARBEITSTAG_MITARBEITER_ID foreign key (MITARBEITER_ID) references PA_MITARBEITER(ID)^
create index IDX_PA_ARBEITSTAG_MITARBEITER on PA_ARBEITSTAG (MITARBEITER_ID)^
-- end PA_ARBEITSTAG
-- begin PA_VORUNTERSUCHUNGSTERMIN
alter table PA_VORUNTERSUCHUNGSTERMIN add constraint FK_PA_VORUNTERSUCHUNGSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID)^
create index IDX_PA_VORUNTERSUCHUNGSTERMIN_PATIENT on PA_VORUNTERSUCHUNGSTERMIN (PATIENT_ID)^
-- end PA_VORUNTERSUCHUNGSTERMIN
-- begin PA_PATIENT
alter table PA_PATIENT add constraint FK_PA_PATIENT_AUGENARZT_ID foreign key (AUGENARZT_ID) references PA_AUGENARZT(ID)^
alter table PA_PATIENT add constraint FK_PA_PATIENT_KRAKENKASSE_ID foreign key (KRAKENKASSE_ID) references PA_KRAKENKASSE(ID)^
create index IDX_PA_PATIENT_KRAKENKASSE on PA_PATIENT (KRAKENKASSE_ID)^
create index IDX_PA_PATIENT_AUGENARZT on PA_PATIENT (AUGENARZT_ID)^
-- end PA_PATIENT
-- begin PA_AUGENARZT_ANGESTELLTE
alter table PA_AUGENARZT_ANGESTELLTE add constraint FK_PA_AUGENARZT_ANGESTELLTE_AUGENARZT_ID foreign key (AUGENARZT_ID) references PA_AUGENARZT(ID)^
create index IDX_PA_AUGENARZT_ANGESTELLTE_AUGENARZT on PA_AUGENARZT_ANGESTELLTE (AUGENARZT_ID)^
-- end PA_AUGENARZT_ANGESTELLTE
