-- begin PA_OPERATIONSTERMIN
alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID)^
alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_RAUM_ID foreign key (RAUM_ID) references PA_RAUM(ID)^
create index IDX_PA_OPERATIONSTERMIN_PATIENT on PA_OPERATIONSTERMIN (PATIENT_ID)^
create index IDX_PA_OPERATIONSTERMIN_RAUM on PA_OPERATIONSTERMIN (RAUM_ID)^
-- end PA_OPERATIONSTERMIN
-- begin PA_OPERATIONSTERMIN_MITARBEITER_LINK
alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_MITARBEITER foreign key (MITARBEITER_ID) references PA_MITARBEITER (ID)^
alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_OPERATIONSTERMIN foreign key (OPERATIONSTERMIN_ID) references PA_OPERATIONSTERMIN (ID)^
-- end PA_OPERATIONSTERMIN_MITARBEITER_LINK
-- begin PA_ARBEITSTAG
alter table PA_ARBEITSTAG add constraint FK_PA_ARBEITSTAG_MITARBEITER_ID foreign key (MITARBEITER_ID) references PA_MITARBEITER(ID)^
create index IDX_PA_ARBEITSTAG_MITARBEITER on PA_ARBEITSTAG (MITARBEITER_ID)^
-- end PA_ARBEITSTAG
-- begin PA_VORUNTERSUCHUNGSTERMIN
alter table PA_VORUNTERSUCHUNGSTERMIN add constraint FK_PA_VORUNTERSUCHUNGSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID)^
create index IDX_PA_VORUNTERSUCHUNGSTERMIN_PATIENT on PA_VORUNTERSUCHUNGSTERMIN (PATIENT_ID)^
-- end PA_VORUNTERSUCHUNGSTERMIN
