alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_MITARBEITER foreign key (MITARBEITER_ID) references PA_MITARBEITER (ID);
alter table PA_OPERATIONSTERMIN_MITARBEITER_LINK add constraint FK_POML_OPERATIONSTERMIN foreign key (OPERATIONSTERMIN_ID) references PA_OPERATIONSTERMIN (ID);
