alter table PA_VORUNTERSUCHUNGSTERMIN add constraint FK_PA_VORUNTERSUCHUNGSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID);
create index IDX_PA_VORUNTERSUCHUNGSTERMIN_PATIENT on PA_VORUNTERSUCHUNGSTERMIN (PATIENT_ID);
