alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_PATIENT_ID foreign key (PATIENT_ID) references PA_PATIENT(ID);
alter table PA_OPERATIONSTERMIN add constraint FK_PA_OPERATIONSTERMIN_RAUM_ID foreign key (RAUM_ID) references PA_RAUM(ID);
create index IDX_PA_OPERATIONSTERMIN_PATIENT on PA_OPERATIONSTERMIN (PATIENT_ID);
create index IDX_PA_OPERATIONSTERMIN_RAUM on PA_OPERATIONSTERMIN (RAUM_ID);
