alter table PA_AUGENARZT_ANGESTELLTE add constraint FK_PA_AUGENARZT_ANGESTELLTE_AUGENARZT_ID foreign key (AUGENARZT_ID) references PA_AUGENARZT(ID);
create index IDX_PA_AUGENARZT_ANGESTELLTE_AUGENARZT on PA_AUGENARZT_ANGESTELLTE (AUGENARZT_ID);
