alter table PA_PATIENT add constraint FK_PA_PATIENT_KRANKENKASSE_ID foreign key (KRANKENKASSE_ID) references PA_KRANKENKASSE(ID);
create index IDX_PA_PATIENT_KRANKENKASSE on PA_PATIENT (KRANKENKASSE_ID);
